modLoader = "javafml"
loaderVersion = "[${forge_version},)"
issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "createtransmission"
version = "${version}"
displayName = "Create: Transmission"
authors = "SerpensSolida"
description = '''
This mod adds a single block: Transmission Chain!

This block can be used to power belts in a cleaner way without using encased chain drive.
'''
logoFile = "icon.png"

[[dependencies.createtransmission]]
modId = "forge"
mandatory = true
versionRange = "[${forge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.createtransmission]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version}"
ordering = "NONE"
side = "BOTH"

[[dependencies.createtransmission]]
modId="create"
mandatory=true
versionRange="${create_version}"
ordering="NONE"
side="BOTH"